### ISSUE TITLE
Project goal

### ISSUE THREAD

**Issue by Cyberzoid1** [Mr-Triangle/Team-2-Project#1]
What should this project do? Some ideas:

- Calculator
- Array flipper  (abcde > edcba)  
- Some kind of algorithm that needs to store numbers for a later use and repeat.

**Comment by tsonnen** [comment]
RPN calculator or the string reversal would be pretty easy to implement

**Comment by Cyberzoid1** [comment]
I'd vote for a calculator. probably just the basic operators 
`+,-,*,/,^,`

We can also add order of operation `a * (b + c)` and/or variable assignment `a = 4`,   ` a + 5`...

Either way we need more of our teammates to pitch in.  So far its only 2/7
